# Generated by Django 4.2.4 on 2025-05-28 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="cat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ingredients",
                to="store.category",
                verbose_name="Category",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orderitem",
            unique_together={("order", "product")},
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="store_order_created_265935_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(fields=["status"], name="store_order_status_428b25_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(
                fields=["is_published", "cat"], name="store_ingre_is_publ_6da61a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredient",
            index=models.Index(fields=["price"], name="store_ingre_price_72e756_idx"),
        ),
    ]
