# Generated by Django 4.2.4 on 2025-05-28 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ingredient",
            old_name="weight",
            new_name="amount",
        ),
    ]
