# Generated by Django 4.2.4 on 2025-06-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_total_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refund_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
