# Generated by Django 4.2.4 on 2025-06-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_order_refund_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="description",
        ),
    ]
