# Generated by Django 4.2.4 on 2025-06-16 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "userprofile",
            "0002_alter_userprofile_options_user_email_verified_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "Users' Profiles",
            },
        ),
    ]
